services:
  unit:
    container_name: ${UNITMAN_UNIT_NAME}.${UNITMAN_PROJECT_NAME}
    restart: always
    privileged: true
    image: docker:26.1.3-dind-rootless
    working_dir: /app
    volumes:
      - ./app:/app
      - ./docker-cache:/var/lib/docker
    env_file:
      - .env.unit

networks:
  default:
    name: unitman_default
    external: true