services:
  unit:
    container_name: ${UNITMAN_UNIT_NAME}.test
    restart: always
    privileged: true
    image: docker:26.1.3-dind
    working_dir: /app
    volumes:
      - ./app:/app
    env_file:
      - .env.unit

networks:
  default:
    name: unitman_default
    external: true