services:
  unit:
    container_name: ${UNITMAN_UNIT_NAME}.${UNITMAN_PROJECT_NAME}
    user: root
    privileged: true
    build:
      context: .
    working_dir: /app
    userns_mode: keep-id
    mem_limit: ${UNITMAN_MEMORY_LIMIT:-3g}
    memswap_limit: ${UNITMAN_MEMORY_LIMIT:-3g}
    volumes:
      - ./../containers:/var/lib/containers
    env_file:
      - .env

networks:
  default:
    external: true
    name: unitman_default
