services:
  unit:
    container_name: ${UNITMAN_UNIT_NAME}.${UNITMAN_PROJECT_NAME}
    user: podman
    privileged: true
    build:
      context: .
    working_dir: /app
    volumes:
      - ./app:/app
      - ./../containers:/var/lib/containers
    env_file:
      - .env.unit

networks:
  default:
    external: true
    name: unitman_default
